sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - npm run lint
  - npm run clean
  - npm run build
  - npm run test
branches:
  only:
    - master
